# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

schedules:
  - cron: "0 17 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
    always: true

steps:
  - task: NodeTool@0
    displayName: 'Install Node 12.x'
    inputs:
      versionSpec: 12.x

  - task: Maven@3
    displayName: Build, test, and deploy with Apache Maven
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'verify'
      options: '-DisHeadless="true" -DBrowser="$(browserName)"'

  - task: PublishCucumberReport@1
    displayName: 'Publish Cucumber Report'
    inputs:
      jsonDir: 'target/cucumberReport/json'
      outputPath: 'target/cucumberReport/cucumber-report-html'
      name: '[$(browserName)] Regression Test for Sprint $(sprintNumber)'
      title: UI Testing

  - task: PublishBuildArtifacts@1
    displayName: Publish Cucumber Report Extension Artifact
    inputs:
      PathtoPublish: '/home/vsts/work/1/s/target/cucumberReport/cucumber-report-html/cucumber-html-reports/'
      ArtifactName: 'Cucumber-Report-Extension'
      publishLocation: 'Container'